FROM python:latest

ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app

COPY ../requirements.txt /app

RUN pip install -r requirements.txt

EXPOSE 5000

RUN pip install redis
RUN pip install gunicorn

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "3", "app:app"]